name: Build JSON

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub
    - name: Run script and commit changes
      run: |
        python release.py
        echo "Setting up git credentials..."
        git remote set-url origin https://x-access-token:"$GITHUB_TOKEN"@github.com/"$GITHUB_REPOSITORY".git
        git config --global user.email "actions@github.com"
        git config --global user.name "actions"
        echo "Git credentials configured."
        
        echo "Pushing new data to repository"
        git checkout master
        git add .
        git commit -m "Automatic update of data"
        git push --set-upstream origin master
        echo "Push complete"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
